services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./.redis-cache:/data
    command: redis-server --appendonly yes

  backend:
    build:
      context: .
      target: backend
    restart: always
    ports:
      - '3001:3001'
    env_file: .env.backend
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./server:/app/server
      - ./tsconfig.json:/app/tsconfig.json
    depends_on:
      - redis
    develop:
      watch:
        - action: rebuild
          path: package.json

  frontend:
    build:
      context: .
      target: frontend
      args:
        LISTEN: '80'
        PROXY_PASS: http://backend:3001
    restart: always
    ports:
      - '5173:80'
    depends_on:
      - backend
    develop:
      watch:
        - action: rebuild
          path: package.json
        - action: rebuild
          path: src/
        - action: rebuild
          path: index.html
